<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8">
        <title>My test page</title>
    </head>
    <body>
        <p>This is my page</p>

        <script>
            let promise = fetch('coffee.jpg');

            let promise2 = promise.then(response => {
                if (!response.ok) {
                    throw new Error(`HTTP error! Status: ${response.status}`);
                } else {
                    return response.blob();
                }
            });

            let promise3 = promise2.then(myBlob => {
                let objectURL = URL.createObjectURL(myBlob);
                let image = document.createElement('img');
                image.src = objectURL;
                document.body.appendChild(image);
            })

            // This block of code adds an error handler, `.catch()`, to "catch" if there are any errors in "fetching" the image.
            // To see this error handler in action, misspell the `coffee.jpg` URL, then load and run the program in your browser.

            let errorCase = promise3.catch(e => {
                console.log('There has been a problem with your fetch operation: ' + e.message);
            });
        </script>
    </body>
</html>